// constants/countries.js
const COUNTRIES = [
  { pt: "Afeganistão", en: "Afghanistan", code: "+93" },
  { pt: "África do Sul", en: "South Africa", code: "+27" },
  { pt: "Albânia", en: "Albania", code: "+355" },
  { pt: "Alemanha", en: "Germany", code: "+49" },
  { pt: "Andorra", en: "Andorra", code: "+376" },
  { pt: "Angola", en: "Angola", code: "+244" },
  { pt: "Antígua e Barbuda", en: "Antigua and Barbuda", code: "+1" },
  { pt: "Arábia Saudita", en: "Saudi Arabia", code: "+966" },
  { pt: "Argélia", en: "Algeria", code: "+213" },
  { pt: "Argentina", en: "Argentina", code: "+54" },
  { pt: "Armênia", en: "Armenia", code: "+374" },
  { pt: "Austrália", en: "Australia", code: "+61" },
  { pt: "Áustria", en: "Austria", code: "+43" },
  { pt: "Azerbaijão", en: "Azerbaijan", code: "+994" },
  { pt: "Bahamas", en: "Bahamas", code: "+1" },
  { pt: "Bahrein", en: "Bahrain", code: "+973" },
  { pt: "Bangladesh", en: "Bangladesh", code: "+880" },
  { pt: "Barbados", en: "Barbados", code: "+1" },
  { pt: "Bélgica", en: "Belgium", code: "+32" },
  { pt: "Belize", en: "Belize", code: "+501" },
  { pt: "Benim", en: "Benin", code: "+229" },
  { pt: "Bielorrússia", en: "Belarus", code: "+375" },
  { pt: "Bolívia", en: "Bolivia", code: "+591" },
  { pt: "Bósnia e Herzegovina", en: "Bosnia and Herzegovina", code: "+387" },
  { pt: "Botsuana", en: "Botswana", code: "+267" },
  { pt: "Brasil", en: "Brazil", code: "+55" },
  { pt: "Brunei", en: "Brunei", code: "+673" },
  { pt: "Bulgária", en: "Bulgaria", code: "+359" },
  { pt: "Burkina Faso", en: "Burkina Faso", code: "+226" },
  { pt: "Burundi", en: "Burundi", code: "+257" },
  { pt: "Butão", en: "Bhutan", code: "+975" },
  { pt: "Cabo Verde", en: "Cape Verde", code: "+238" },
  { pt: "Camarões", en: "Cameroon", code: "+237" },
  { pt: "Camboja", en: "Cambodia", code: "+855" },
  { pt: "Canadá", en: "Canada", code: "+1" },
  { pt: "Catar", en: "Qatar", code: "+974" },
  { pt: "Cazaquistão", en: "Kazakhstan", code: "+7" },
  { pt: "Chade", en: "Chad", code: "+235" },
  { pt: "Chile", en: "Chile", code: "+56" },
  { pt: "China", en: "China", code: "+86" },
  { pt: "Chipre", en: "Cyprus", code: "+357" },
  { pt: "Colômbia", en: "Colombia", code: "+57" },
  { pt: "Comores", en: "Comoros", code: "+269" },
  { pt: "Congo", en: "Republic of the Congo", code: "+242" },
  { pt: "Congo, República Democrática do", en: "Democratic Republic of the Congo", code: "+243" },
  { pt: "Coreia do Norte", en: "North Korea", code: "+850" },
  { pt: "Coreia do Sul", en: "South Korea", code: "+82" },
  { pt: "Costa do Marfim", en: "Ivory Coast", code: "+225" },
  { pt: "Costa Rica", en: "Costa Rica", code: "+506" },
  { pt: "Croácia", en: "Croatia", code: "+385" },
  { pt: "Cuba", en: "Cuba", code: "+53" },
  { pt: "Dinamarca", en: "Denmark", code: "+45" },
  { pt: "Djibuti", en: "Djibouti", code: "+253" },
  { pt: "Dominica", en: "Dominica", code: "+1" },
  { pt: "Egito", en: "Egypt", code: "+20" },
  { pt: "El Salvador", en: "El Salvador", code: "+503" },
  { pt: "Emirados Árabes Unidos", en: "United Arab Emirates", code: "+971" },
  { pt: "Equador", en: "Ecuador", code: "+593" },
  { pt: "Eritreia", en: "Eritrea", code: "+291" },
  { pt: "Eslováquia", en: "Slovakia", code: "+421" },
  { pt: "Eslovênia", en: "Slovenia", code: "+386" },
  { pt: "Espanha", en: "Spain", code: "+34" },
  { pt: "Estados Unidos", en: "United States", code: "+1" },
  { pt: "Estônia", en: "Estonia", code: "+372" },
  { pt: "Eswatini", en: "Eswatini", code: "+268" },
  { pt: "Etiópia", en: "Ethiopia", code: "+251" },
  { pt: "Fiji", en: "Fiji", code: "+679" },
  { pt: "Filipinas", en: "Philippines", code: "+63" },
  { pt: "Finlândia", en: "Finland", code: "+358" },
  { pt: "França", en: "France", code: "+33" },
  { pt: "Gabão", en: "Gabon", code: "+241" },
  { pt: "Gâmbia", en: "Gambia", code: "+220" },
  { pt: "Gana", en: "Ghana", code: "+233" },
  { pt: "Geórgia", en: "Georgia", code: "+995" },
  { pt: "Granada", en: "Grenada", code: "+1" },
  { pt: "Grécia", en: "Greece", code: "+30" },
  { pt: "Guatemala", en: "Guatemala", code: "+502" },
  { pt: "Guiana", en: "Guyana", code: "+592" },
  { pt: "Guiné", en: "Guinea", code: "+224" },
  { pt: "Guiné Equatorial", en: "Equatorial Guinea", code: "+240" },
  { pt: "Guiné-Bissau", en: "Guinea-Bissau", code: "+245" },
  { pt: "Haiti", en: "Haiti", code: "+509" },
  { pt: "Honduras", en: "Honduras", code: "+504" },
  { pt: "Hungria", en: "Hungary", code: "+36" },
  { pt: "Iêmen", en: "Yemen", code: "+967" },
  { pt: "Ilhas Marshall", en: "Marshall Islands", code: "+692" },
  { pt: "Ilhas Salomão", en: "Solomon Islands", code: "+677" },
  { pt: "Índia", en: "India", code: "+91" },
  { pt: "Indonésia", en: "Indonesia", code: "+62" },
  { pt: "Irã", en: "Iran", code: "+98" },
  { pt: "Iraque", en: "Iraq", code: "+964" },
  { pt: "Irlanda", en: "Ireland", code: "+353" },
  { pt: "Islândia", en: "Iceland", code: "+354" },
  { pt: "Israel", en: "Israel", code: "+972" },
  { pt: "Itália", en: "Italy", code: "+39" },
  { pt: "Jamaica", en: "Jamaica", code: "+1" },
  { pt: "Japão", en: "Japan", code: "+81" },
  { pt: "Jordânia", en: "Jordan", code: "+962" },
  { pt: "Kiribati", en: "Kiribati", code: "+686" },
  { pt: "Kuwait", en: "Kuwait", code: "+965" },
  { pt: "Laos", en: "Laos", code: "+856" },
  { pt: "Lesoto", en: "Lesotho", code: "+266" },
  { pt: "Letônia", en: "Latvia", code: "+371" },
  { pt: "Líbano", en: "Lebanon", code: "+961" },
  { pt: "Libéria", en: "Liberia", code: "+231" },
  { pt: "Líbia", en: "Libya", code: "+218" },
  { pt: "Liechtenstein", en: "Liechtenstein", code: "+423" },
  { pt: "Lituânia", en: "Lithuania", code: "+370" },
  { pt: "Luxemburgo", en: "Luxembourg", code: "+352" },
  { pt: "Macedônia do Norte", en: "North Macedonia", code: "+389" },
  { pt: "Madagáscar", en: "Madagascar", code: "+261" },
  { pt: "Malásia", en: "Malaysia", code: "+60" },
  { pt: "Malaui", en: "Malawi", code: "+265" },
  { pt: "Maldivas", en: "Maldives", code: "+960" },
  { pt: "Mali", en: "Mali", code: "+223" },
  { pt: "Malta", en: "Malta", code: "+356" },
  { pt: "Marrocos", en: "Morocco", code: "+212" },
  { pt: "Maurício", en: "Mauritius", code: "+230" },
  { pt: "Mauritânia", en: "Mauritania", code: "+222" },
  { pt: "México", en: "Mexico", code: "+52" },
  { pt: "Mianmar", en: "Myanmar", code: "+95" },
  { pt: "Micronésia", en: "Micronesia", code: "+691" },
  { pt: "Moçambique", en: "Mozambique", code: "+258" },
  { pt: "Moldávia", en: "Moldova", code: "+373" },
  { pt: "Mônaco", en: "Monaco", code: "+377" },
  { pt: "Mongólia", en: "Mongolia", code: "+976" },
  { pt: "Montenegro", en: "Montenegro", code: "+382" },
  { pt: "Namíbia", en: "Namibia", code: "+264" },
  { pt: "Nauru", en: "Nauru", code: "+674" },
  { pt: "Nepal", en: "Nepal", code: "+977" },
  { pt: "Nicarágua", en: "Nicaragua", code: "+505" },
  { pt: "Níger", en: "Niger", code: "+227" },
  { pt: "Nigéria", en: "Nigeria", code: "+234" },
  { pt: "Noruega", en: "Norway", code: "+47" },
  { pt: "Nova Zelândia", en: "New Zealand", code: "+64" },
  { pt: "Omã", en: "Oman", code: "+968" },
  { pt: "Países Baixos", en: "Netherlands", code: "+31" },
  { pt: "Palau", en: "Palau", code: "+680" },
  { pt: "Panamá", en: "Panama", code: "+507" },
  { pt: "Papua Nova Guiné", en: "Papua New Guinea", code: "+675" },
  { pt: "Paquistão", en: "Pakistan", code: "+92" },
  { pt: "Paraguai", en: "Paraguay", code: "+595" },
  { pt: "Peru", en: "Peru", code: "+51" },
  { pt: "Polônia", en: "Poland", code: "+48" },
  { pt: "Portugal", en: "Portugal", code: "+351" },
  { pt: "Quênia", en: "Kenya", code: "+254" },
  { pt: "Quirguistão", en: "Kyrgyzstan", code: "+996" },
  { pt: "Reino Unido", en: "United Kingdom", code: "+44" },
  { pt: "República Centro-Africana", en: "Central African Republic", code: "+236" },
  { pt: "República Dominicana", en: "Dominican Republic", code: "+1" },
  { pt: "República Tcheca", en: "Czech Republic", code: "+420" },
  { pt: "Romênia", en: "Romania", code: "+40" },
  { pt: "Ruanda", en: "Rwanda", code: "+250" },
  { pt: "Rússia", en: "Russia", code: "+7" },
  { pt: "Samoa", en: "Samoa", code: "+685" },
  { pt: "San Marino", en: "San Marino", code: "+378" },
  { pt: "Santa Lúcia", en: "Saint Lucia", code: "+1" },
  { pt: "São Cristóvão e Nevis", en: "Saint Kitts and Nevis", code: "+1" },
  { pt: "São Tomé e Príncipe", en: "São Tomé and Príncipe", code: "+239" },
  { pt: "São Vicente e Granadinas", en: "Saint Vincent and the Grenadines", code: "+1" },
  { pt: "Seicheles", en: "Seychelles", code: "+248" },
  { pt: "Senegal", en: "Senegal", code: "+221" },
  { pt: "Serra Leoa", en: "Sierra Leone", code: "+232" },
  { pt: "Sérvia", en: "Serbia", code: "+381" },
  { pt: "Singapura", en: "Singapore", code: "+65" },
  { pt: "Síria", en: "Syria", code: "+963" },
  { pt: "Somália", en: "Somalia", code: "+252" },
  { pt: "Sri Lanka", en: "Sri Lanka", code: "+94" },
  { pt: "Sudão", en: "Sudan", code: "+249" },
  { pt: "Sudão do Sul", en: "South Sudan", code: "+211" },
  { pt: "Suécia", en: "Sweden", code: "+46" },
  { pt: "Suíça", en: "Switzerland", code: "+41" },
  { pt: "Suriname", en: "Suriname", code: "+597" },
  { pt: "Tailândia", en: "Thailand", code: "+66" },
  { pt: "Taiwan*", en: "Taiwan", code: "+886" },
  { pt: "Tajiquistão", en: "Tajikistan", code: "+992" },
  { pt: "Tanzânia", en: "Tanzania", code: "+255" },
  { pt: "Tchéquia", en: "Czechia", code: "+420" },
  { pt: "Timor-Leste", en: "East Timor", code: "+670" },
  { pt: "Togo", en: "Togo", code: "+228" },
  { pt: "Tonga", en: "Tonga", code: "+676" },
  { pt: "Trinidad e Tobago", en: "Trinidad and Tobago", code: "+1" },
  { pt: "Tunísia", en: "Tunisia", code: "+216" },
  { pt: "Turcomenistão", en: "Turkmenistan", code: "+993" },
  { pt: "Turquia", en: "Turkey", code: "+90" },
  { pt: "Tuvalu", en: "Tuvalu", code: "+688" },
  { pt: "Ucrânia", en: "Ukraine", code: "+380" },
  { pt: "Uganda", en: "Uganda", code: "+256" },
  { pt: "Uruguai", en: "Uruguay", code: "+598" },
  { pt: "Uzbequistão", en: "Uzbekistan", code: "+998" },
  { pt: "Vanuatu", en: "Vanuatu", code: "+678" },
  { pt: "Vaticano", en: "Vatican City", code: "+379" },
  { pt: "Venezuela", en: "Venezuela", code: "+58" },
  { pt: "Vietnã", en: "Vietnam", code: "+84" },
  { pt: "Zâmbia", en: "Zambia", code: "+260" },
  { pt: "Zimbábue", en: "Zimbabwe", code: "+263" }
];

export default COUNTRIES;