import {
  Package,
  Map,
  Users,
  ChartNoAxesColumn,
  DollarSign,
  Bell,
  Home,
  Truck,
  Check,
  X,
  Plus,
  Eye,
  LogOut,
  AlertCircle,
  Star,
  Settings,
  MapPin,
  Clock,
  ShoppingBag,
  User,
  FileText,
  Image,
  Upload,
  Filter,
  Search,
  Edit,
  Trash2,
  Tag,
  Store,
  Warehouse,
  Calendar,
  MessageSquare,
  Shield,
  Wrench,
  AlertTriangle,
  MoreHorizontal,
  Phone,
  CreditCard,
  Navigation,
  ThumbsUp,
  ThumbsDown,
  ChevronLeft,
  ChevronRight,
  Send,
  Camera,
  Menu,
  Heart,
  Share2,
  Info,
  HelpCircle,
  Power,
  Moon,
  Sun,
  Globe,
  Smartphone,
  QrCode,
  Receipt,
  Award,
  Gift,
  TrendingUp,
  Clock as ClockIcon,
  History,
  MapPin as MapPinIcon,
  CheckCircle,
  XCircle,
  AlertOctagon,
  RefreshCw,
  Mic,
  Copy,
  ExternalLink,
  FileText as FileTextIcon,
  Printer,
  Download,
  Mail,
  MessageCircle,
  Facebook,
  Twitter,
  ClipboardList,
  MailCheck,
  PlusCircle,
  Zap,
  Headphones
} from "lucide-react"




// ─── ICONS (Lucide React) ───────────────────────────────────────────────────────
const Icon = ({ name, size = 20, className = "" }) => {
  const icons = {
    clipboard: ClipboardList,
    package: Package,
    map: Map,
    users: Users,
    chart: ChartNoAxesColumn,
    dollar: DollarSign,
    bell: Bell,
    home: Home,
    truck: Truck,
    check: Check,
    x: X,
    plus: Plus,
    zap: Zap,
    headphones: Headphones,
    PlusCircle:PlusCircle,
    eye: Eye,
    logout: LogOut,
    alert: AlertCircle,
    star: Star,
    settings: Settings,
    location: MapPin,
    clock: Clock,
    shopping: ShoppingBag,
    user: User,
    file: FileText,
    image: Image,
    upload: Upload,
    filter: Filter,
    search: Search,
    edit: Edit,
    trash: Trash2,
    tag: Tag,
    store: Store,
    warehouse: Warehouse,
    calendar: Calendar,
    message: MessageSquare,
    shield: Shield,
    wrench: Wrench,
    alertTriangle: AlertTriangle,
    more: MoreHorizontal,
    phone: Phone,
    creditCard: CreditCard,
    navigation: Navigation,
    thumbsUp: ThumbsUp,
    thumbsDown: ThumbsDown,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    send: Send,
    camera: Camera,
    menu: Menu,
    heart: Heart,
    share2: Share2,
    info: Info,
    helpCircle: HelpCircle,
    power: Power,
    moon: Moon,
    sun: Sun,
    globe: Globe,
    smartphone: Smartphone,
    qrCode: QrCode,
    receipt: Receipt,
    award: Award,
    gift: Gift,
    trendingUp: TrendingUp,
    clockIcon: ClockIcon,
    history: History,
    mapPin: MapPinIcon,
    checkCircle: CheckCircle,
    xCircle: XCircle,
    alertOctagon: AlertOctagon,
    refreshCw: RefreshCw,
    mic: Mic,
    copy: Copy,
    externalLink: ExternalLink,
    fileText: FileTextIcon,
    printer: Printer,
    download: Download,
    mail: Mail,
    messageCircle: MessageCircle,
    whatsapp: MessageCircle,
    facebook: Facebook,
    twitter: Twitter,
    mailCheck: MailCheck
  };

  const LucideIcon = icons[name];
  
  if (!LucideIcon) return null;
  
  return <LucideIcon size={size} className={className} />;
};



export default Icon